### ISSUE TITLE
broken serialization for subclass of MutableMapping

### ISSUE THREAD

**Issue by gshank** [Fatal1ty/mashumaro#48] opened 2021-04-23 01:48 UTC
Commit 501b648c4d6b5d60f419c168a1e7c49d1417cdf0 broke Mashumaro for our project (dbt). The problem appears to be that Python reports None as the origin for one of our classes that inherits from a class that also inherits from MutableMapping.

There is a test at https://github.com/gshank/mashumaro/blob/broken_config/tests/test_mutable_mapping.py. This test passes on Python 3.6 but is broken in Python 3.8.

I made an attempt to fix it but just went around in circles. Putting back the 'is_dataclass' calls that were removed in the breaking commit fixed this test, but broke two other tests: tests/test_data_types.py::test_dataclass_field_without_mixin and tests/test_data_types.py::test_serializable_type_dataclass.

**Comment by Fatal1ty** [comment] 2021-04-23 08:37
Hello @gshank

The problem is caused by moving `is_dataclass_dict_mixin_subclass` call to the very bottom. Can you check [this branch ](https://github.com/Fatal1ty/mashumaro/tree/move-dataclass-check)and tell me if everything is ok?

**Comment by gshank** [comment] 2021-04-23 13:51
That fixed the original problem, but now there's a different problem. I'll see if I can create a test case.

The MutableMapping subclass has caused a number of difficulties because there seems to be a number of Python holes in that area. I may try to change our code to not do that.

**Comment by gshank** [comment] 2021-04-23 14:22
This next problem started with commit e8f58d34c00064ca3673f4f0d5bed4d2b8b56da4.

The error is: mashumaro.exceptions.InvalidFieldValue: Field "version" of type typing.Union[__main__.SemverString, float] in __main__.Project has invalid value '0.0.1'

Test:

#!/usr/bin/env python
from typing import Union
from dataclasses import dataclass
from mashumaro import DataClassDictMixin
from mashumaro.types import SerializableType


class SemverString(str, SerializableType):
    def _serialize(self) -> str:
        return self

    @classmethod
    def _deserialize(cls, value: str) -> 'SemverString':
        return SemverString(value)


@dataclass                                                               
class Project(DataClassDictMixin):                                              
    name: str                                  
    version: Union[SemverString, float]


project_dict = {
    'name': 'my_test_project',
    'version': '0.0.1',
}

project = Project.from_dict(project_dict)

**Comment by gshank** [comment] 2021-04-23 14:24
The formatting got weird on that test. Here is a gist: https://gist.github.com/gshank/22cb064bee2dd752c7cd8d69c38fdcc1

**Comment by Fatal1ty** [comment] 2021-04-23 14:55
> The formatting got weird on that test. Here is a gist: https://gist.github.com/gshank/22cb064bee2dd752c7cd8d69c38fdcc1

@gshank Thank you for spotting this bug. I fixed it in the latest commit of the same [branch](https://github.com/Fatal1ty/mashumaro/tree/move-dataclass-check). Can you check it out again?

**Comment by Fatal1ty** [comment] 2021-04-28 19:02
Fixed in 2.5.

**Closed by Fatal1ty** 2021-04-28 19:02 UTC

**Comment by gshank** [comment] 2021-04-28 19:04
Sorry for the delay; I was working on other things. This works great for this bug! 

We are extending our use of mashumaro to some new classes in our codebase (to use msgpack) and I have run into an issue with tuples for dictionary keys, but I will open a new issue since it's not related to these.

Thanks for your good work.
