### ISSUE TITLE
Using `InitVar` with mashumaro

### ISSUE THREAD

**Issue by garethr** [Fatal1ty/mashumaro#8] opened 2019-06-22 12:36 UTC
First up, thanks for the library. It's providing really useful for something I started working on.

I've run into one problem. I'd like some properties of the dataclass to be ignored for most purposes. `InitVar` appears ideal for this usecase, https://docs.python.org/3/library/dataclasses.html#init-only-variables

> If a field is an InitVar, it is considered a pseudo-field called an init-only field. As it is not a true field, it is not returned by the module-level fields() function. Init-only fields are added as parameters to the generated __init__() method, and are passed to the optional __post_init__() method. They are not otherwise used by dataclasses.

However, adding an InitVar seems to trip mashuramo. It complains that it's not serializable. I would expect InitVars to be ignored, because they are explicitly not intended to be part of the final serialisation.

```python
class Organization(object):
     api_token: InitVar[str] = None
```

```
raise UnserializableField(fname, ftype, parent)
mashumaro.exceptions.UnserializableField: Field "api_token" of type dataclasses.InitVar in models.Organization is not serializable
```

* Are there any work arounds at the moment? 
* Does the above make sense, should InitVars be ignored by mashuramo's validation?

**Comment by Fatal1ty** [comment] 2019-06-22 12:52
I’ve missed that and totally agree with you Of course, InitVars should be ignored. Unfortunately, there are no workarounds at the moment but I‘ll dive into the problem and release a new version today.

**Comment by Fatal1ty** [comment] 2019-06-22 12:53
I’ve missed that and totally agree with you. Certainly, InitVars should be ignored. Unfortunately, there are no workarounds at the moment but I‘ll dive into the problem and release a new version today.

**Comment by Fatal1ty** [comment] 2019-06-22 14:47
Fixed in 1.7

**Comment by garethr** [comment] 2019-06-22 14:51
@Fatal1ty thanks a lot for the super quick fix. I've just checked this as well and I can confirm it resolves my issue. Much appreciated.

**Comment by Fatal1ty** [comment] 2019-06-22 14:51
By the way, thanks for the detailed description. If the problem is solved, we can close this issue.

**Closed** 2019-06-22 14:51 UTC
