### ISSUE TITLE
Pass dialect to SerializableType types

### ISSUE THREAD

**Issue by mishamsk** [Fatal1ty/mashumaro#100] opened 2023-03-09 17:56 UTC
**Is your feature request related to a problem? Please describe.**
I am using SerializableType heavily, including for customization of mixin-derived classes themselves (as discussed in #92). Since serialization to msg pack, Orson requires different dialects, this dialect has to be passed down to `_serialize` and `_deserialize` functions somehow. 

**Describe the solution you'd like**
Ideally, mashumaro will add an optional dialect call parameter to `_serialize` and `_deserialize` when dialects are enabled mirroring `to_dict` and `from_dict`

**Describe alternatives you've considered**
I currently rely on base class and a class variable that stores a chosen dialect, but that mandates creating "alternative" `to_dict`/`from_dict` dict functions (I call them `as_dict`/`as_obj` because I must have access to generated once). These alternatives merely save the passed in dialect and then pass the execution down to generated `to_dict`/`from_dict`.

**Additional context**
see linked issue and our previous discussion.

**Comment by mishamsk** [comment] 2023-03-10 19:47
btw. happy to implement it myself, if you are ok with PR's

**Comment by Fatal1ty** [comment] 2023-03-17 08:32
Hi. Sorry for delay, I need more time to think about. The problem is that `SerializableType` is meant to be as simple as possible but you're on the path of adding dialect functionality inside `SerializableType`, but it contradicts what we already have. You can use `SerializableType` with `use_annotations=True` argument (as noted in the [docs](https://github.com/Fatal1ty/mashumaro#serializabletype-interface)) and apply the specific dialect outside — in the scope where `SerializableType` subclass is used. Before passing data to `SerializableType._deserialize` that data is prepared according to the dialect. I suggest that we think about going down this way and solving problems that arise.

**Comment by mishamsk** [comment] 2023-03-18 14:33
Hi, no worries. I understand the preference to keep it simple, however, I would argue that dialect, being an attribute of generated methods is ok to pass down.

Consider slightly extended example from that doc:
```python
from dataclasses import dataclass
from datetime import datetime
from typing import Any
from mashumaro.mixins.msgpack import DataClassMessagePackMixin
from mashumaro.mixins.orjson import DataClassORJSONMixin
from mashumaro.mixins.dict import DataClassDictMixin
from mashumaro.types import SerializableType

class Airport(SerializableType):
    def __init__(self, code, city):
        self.code, self.city = code, city

    def _serialize(self):
        return [self.code, self.city]

    @classmethod
    def _deserialize(cls, value):
        return cls(*value)

    def __eq__(self, other):
        return self.code, self.city == other.code, other.city

@dataclass
class Flight(DataClassDictMixin):
    origin: Airport
    destination: Airport

class Itinerary(SerializableType, use_annotations=True):
    def __init__(self, flights: list[Flight], date: datetime, docs: bytes):
        self.flights = flights
        self.departure_date = datetime.now()
        self.docs = docs

    def _serialize(self) -> dict[str, Any]:
        return {"flights": self.flights, "date": self.departure_date.isoformat(), "docs": self.docs.decode()}

    @classmethod
    def _deserialize(cls, flights):
        return cls(flights)

@dataclass
class TravelPlan(DataClassMessagePackMixin, DataClassORJSONMixin):
    budget: float
    itinerary: Itinerary

input_data = {
    "budget": 10_000,
    "itinerary": [
        {
            "origin": ["JFK", "New York City"],
            "destination": ["LAX", "Los Angeles"]
        },
        {
            "origin": ["LAX", "Los Angeles"],
            "destination": ["SFO", "San Fransisco"]
        }
    ]
}
```

Couple issues here:
1. I can't really use the `use_annotations=True`, do I? 
2. Even if I would. Notice I've used msg pack & orjson mixins on the root class. They both define different dialects that affect how bytes and dates must be serialized. How can one make the `Itinerary` compatible with them without know the current dialect? We may indeed mingle with `_deserialize` in the root (which would force us tom make it a custom serizliable type as well, unnecessarily), but what about `serialize` in `Itinerary`? By the time `departure_date` and `docs` has reached the root class they are already serialized according to logic that is not aware of the current dialect.

This is not a hypothetical scenario. This is actually exactly how I use it in my serialization wrapper around mashumaro (which would probably make sense to become part of mashumaro itself). I will open source my AST library which includes it, hopefully by PyCon (April 20th), so I could just point to the code I wrote to make a more vivid explanation.

**Comment by Fatal1ty** [comment] 2023-03-19 12:28
Perhaps, the documentation doesn't clearly describe the use of the `use_annotation` parameter. I admit that it might have been worth writing more about it, but since it's mostly optional feature to use in the current version, I planned to write more in the next major version, where `use_annotations` will become `True` by default.

The second point. At first glance, it may seem that `_serialize` and `_deserialize` methods are meant to work with basic types (like `str` or `int` but not `datetime`) that are supported by most encoders, and I see from your example that you may have fallen into this trap. In fact, before the appearance of `use_annotations=True` feature in practice, it was so. Now with the introduction of this functionality, you can do the following:
* Return from `_serialize` method the data of any type that is able to be used in `to_*` methods in the root dataclass with or without a dialect
* Pass to `_deserialize` method the data of any type that is able to be used in `from_*` methods of the root dataclass with or without dialect

So, if a root dataclass can serialize datetime with a specific dialect for orjson, then you can just return a `datetime` object from `_serialize` and be sure that this dialect will be used. In addition, `_serialize` can return any other custom third-party data type that is supported by the root dataclass. All this is also applicable vice versa — for deserialization with `_deserialize` method.

Now going back to the example above, we need to do the following:
1) Remove `isoformat()` and `decode()` and just use `Itinerary` attributes as is.
2) Since `dict[str, Any]` is too broad we need to replace it with more precise type. `TypedDict` is our choice.

```python
class ItineraryDict(TypedDict):
    flights: list[Flight]
    date: datetime
    docs: bytes

class Itinerary(SerializableType, use_annotations=True):
    def __init__(self, flights: list[Flight], date: datetime, docs: bytes):
        self.flights = flights
        self.departure_date = date
        self.docs = docs

    def _serialize(self) -> ItineraryDict:
        return {
            "flights": self.flights,
            "date": self.departure_date,
            "docs": self.docs,
        }

    @classmethod
    def _deserialize(cls, value: ItineraryDict) -> "Itinerary":
        return cls(
            flights=value["flights"], date=value["date"], docs=value["docs"]
        )
```

And now let's use our modified code:
```python
plan = TravelPlan(
    budget=3.14,
    itinerary=Itinerary(
        flights=[
            Flight(
                origin=Airport("JFK", "New York City"),
                destination=Airport("LAX", "Los Angeles"),
            )
        ],
        date=datetime(2023, 3, 19, 12, 0),
        docs=b"abc",
    ),
)
```

Here everything will be serialized using default serialization stragy:
```python
plan.to_dict()
```

Here `docs` will be passed to `msgpack.packb` as is because of [`MessagePackDialect`](https://github.com/Fatal1ty/mashumaro/blob/master/mashumaro/mixins/msgpack.py#L19)'s serialization strategy:
```python
plan.to_msgpack()
```
Here `date ` will be passed to `orjson.dumps` as is because of [`OrjsonDialect`](https://github.com/Fatal1ty/mashumaro/blob/master/mashumaro/mixins/orjson.py#L22)'s serialization strategy:
```python
plan.to_jsonb()
```

To demonstrate the power of annotations more let's allow the use of third-party dialects in our root dataclass `TravelPlan` and create a dialect for `datetime`:
```python
@dataclass
class TravelPlan(DataClassMessagePackMixin, DataClassORJSONMixin):
    budget: float
    itinerary: Itinerary

    class Config(BaseConfig):
        code_generation_options = [ADD_DIALECT_SUPPORT]

class TimestampDialect(Dialect):
    serialization_strategy = {
        datetime: {
            "serialize": datetime.timestamp,
            "deserialize": datetime.fromtimestamp,
        }
    }
```

Now you can call `to_*` and `from_*` methods and be sure that this `TimestampDialect` will be used for the departure date:
```python
dumped = plan.to_jsonb(dialect=TimestampDialect)
print(dumped)
# b'{"budget":3.14,"itinerary":{"flights":[{"origin":["JFK","New York City"],"destination":["LAX","Los Angeles"]}],"date":1679216400.0,"docs":"YWJj\\n"}}'
assert (
    plan.itinerary.departure_date
    == TravelPlan.from_json(
        dumped, dialect=TimestampDialect
    ).itinerary.departure_date
)
```

I hope I helped you figure out how `use_annotations` was intended to be used, and that this approach allows you to solve the original problem that led to this issue.

> This is actually exactly how I use it in my serialization wrapper around mashumaro (which would probably make sense to become part of mashumaro itself). I will open source my AST library which includes it, hopefully by PyCon (April 20th), so I could just point to the code I wrote to make a more vivid explanation.

This sounds very interesting! I will be looking forward to your presentation, which I will definitely watch if it's going to be available online.

**Comment by mishamsk** [comment] 2023-03-19 19:54
> Since dict[str, Any] is too broad we need to replace it with more precise type. TypedDict is our choice.
ah! Forgot you support that. 

Ok now it makes sense. Thanks a lot for elaborate description. I'll need to think if this would make my wrapper simpler, I may refactor it.

> This sounds very interesting! I will be looking forward to your presentation, which I will definitely watch if it's going to be available online.

Unfortunately not speaking yet, just attending and wanted to have it public in case I'll use the opportunity to socialize the framework. Python is definitely not the language of choice for compilation/transpilation (which my library is geared for), but there are a couple of notable projects like [sqlglot](https://github.com/tobymao/sqlglot) that do that, and I am in the same bandwagon.

You can close the issue if you'd like or wait until I assess if this would solve all of my cases. I am not yet sure TBH

**Comment by Fatal1ty** [comment] 2023-03-19 20:19
> You can close the issue if you'd like or wait until I assess if this would solve all of my cases. I am not yet sure TBH

Do you know an approximate time when you'll be able to try a new approach in your wrapper? I don't mind leaving this issue open if it can happen soon.

**Comment by mishamsk** [comment] 2023-03-20 04:45
I am swamped for the next 2 weeks, but hopefully will get to it after that

**Comment by Fatal1ty** [comment] 2023-07-25 12:00
Hey @mishamsk 

Any news? :)

**Comment by mishamsk** [comment] 2023-07-26 13:22
@Fatal1ty hey! you can clearly see I am really bad at timelines;-) tbh I did some prep work two weeks ago to make the lib less intertwined with the commercial project it is used in, now it is a matter of setting it up as an OSS package with all the publishing, docs and other bells and whistles. Didn't get to it yet...

I was also trying to use the 3.8 contexts & discriminated unions to try to eliminate my custom extension for mashumaro. It didn't work and I now have more feature-requests or pull requests that I wanted to open.

Given how long it takes me, feel free to close this issue. I'll just open new ones when I'll manage to publish the lib and it would be a more constructive dialog.

P.S. rest assured we continue to use mashumaro a lot!

**Comment by Fatal1ty** [comment] 2023-07-26 13:45
@mishamsk

Ok, I will close this issue then. You're always welcome to open new ones :)

**Closed by Fatal1ty** 2023-07-26 13:45 UTC
Labels: needs information
