### ISSUE TITLE
to_dict/to_json not working with postponed annotations for Generic dataclass, if typed class is defined in different module 

### ISSUE THREAD

**Issue by AntonOvsyannikov** [Fatal1ty/mashumaro#90] opened 2022-12-13 19:51 UTC
* mashumaro version: 3.1
* Python version: 3.11
* Operating System: Win11

### Description
In all my modules I am using postponed annotations.
```
from __future__ import annotations
```
I define `dataclass`, inherited from `Generic[T]`, where typevar is defined in same module. Than I derive some typed class and try to call `to_dict()`. If both classes are in same module enerything is ok. If typed class defined in different module I got `UnresolvedTypeReferenceError`
### What I Did

`m1.py`
```
from __future__ import annotations  # w/o is ok
from dataclasses import dataclass
from typing import TypeVar, Generic

from mashumaro.mixins.json import DataClassJSONMixin

T = TypeVar("T")


@dataclass
class Foo(Generic[T], DataClassJSONMixin):
    x: T


@dataclass
class Bar(Foo[int]):
    ...
```

`m2.py`
```
from __future__ import annotations

from dataclasses import dataclass
from typing import TypeVar

from m1 import Foo, Bar


# T = TypeVar("T") # if I uncomment this line, the error goes away


@dataclass
class Baz(Foo[int]):
    ...


print(Bar(x=1).to_json())  # ok
print(Baz(x=1).to_json())  # mashumaro.exceptions.UnresolvedTypeReferenceError: Class Baz has unresolved type reference T in some of its fields
```

**Comment by Fatal1ty** [comment] 2022-12-13 20:38
Hi @AntonOvsyannikov 

Thank you for the illustrative example. In my production code I don't use postponed annotations, that's why this problem hadn't been discovered before you did :)

This bug seems to be caused by explicit passing globals of the `Baz`'s module to `typing.get_type_hints` [here](https://github.com/Fatal1ty/mashumaro/blob/master/mashumaro/core/meta/code/builder.py#L113-L118). Without it `typing.get_type_hints` would get globals of the base class, in our example `Foo`, [here](https://github.com/python/cpython/blob/main/Lib/typing.py#L2305). At first glance the fix is straightforward, but I have to think about this more carefully just so as not to break something else.

**Comment by Fatal1ty** [comment] 2022-12-23 23:57
Hi @AntonOvsyannikov 

I came to conclusion to remove explicit globals and locals passing to `typing.get_type_hints` that will definitely solve this issue. All the tests are passing and it seems not to break something. Anyway, it would be nice if you check [this](https://github.com/Fatal1ty/mashumaro/tree/fix-get-type-hints) branch before going to release.

**Comment by mishamsk** [comment] 2023-01-05 00:09
@Fatal1ty while @AntonOvsyannikov is out sick, let me chime in here. I can confirm that the fix works for the sample code. However, on our actual project code, as soon as I switch from 3.3 to the "fix" branch code, I get `RecursionError`. 

It is hard for me to extract only the relevant code and I haven't created a clean sample to reproduce the bug yet, but will try to explain in case you'll manage to figure it out right away.

We have a generic base class, that among other things inherits DataClassJSONMixin and implements an __init_subclass__ . On the first import of a subclass (similar to the example above), init_subclass chain triggers mixin compiler with the following traceback:
```
File "/Users/misha/Dev/mashumaro/mashumaro/mixins/dict.py", line 25, in __init_subclass__
    compile_mixin_packer(cls, **builder_params["packer"])
File "/Users/misha/Dev/mashumaro/mashumaro/core/meta/mixin.py", line 29, in compile_mixin_packer
    builder.add_pack_method()
```
followed by an infinite loop until python breaks on recursion depth.
```
File "/Users/misha/Dev/mashumaro/mashumaro/core/meta/code/builder.py", line 852, in add_pack_method
    self._add_pack_method_lines(method_name)
  File "/Users/misha/Dev/mashumaro/mashumaro/core/meta/code/builder.py", line 682, in _add_pack_method_lines
    packer, alias, could_be_none = self._get_field_packer(
  File "/Users/misha/Dev/mashumaro/mashumaro/core/meta/code/builder.py", line 876, in _get_field_packer
    packer = PackerRegistry.get(
  File "/Users/misha/Dev/mashumaro/mashumaro/core/meta/types/common.py", line 86, in get
    expr = packer(spec)
  File "/Users/misha/Dev/mashumaro/mashumaro/core/meta/types/pack.py", line 315, in pack_special_typing_primitive
    pv = PackerRegistry.get(spec.copy(type=arg))
  File "/Users/misha/Dev/mashumaro/mashumaro/core/meta/types/common.py", line 86, in get
    expr = packer(spec)
  File "/Users/misha/Dev/mashumaro/mashumaro/core/meta/types/pack.py", line 193, in pack_dataclass_dict_mixin_subclass
    builder.add_pack_method()
  File "/Users/misha/Dev/mashumaro/mashumaro/core/meta/code/builder.py", line 852, in add_pack_method
    self._add_pack_method_lines(method_name)
  File "/Users/misha/Dev/mashumaro/mashumaro/core/meta/code/builder.py", line 682, in _add_pack_method_lines
    packer, alias, could_be_none = self._get_field_packer(
  File "/Users/misha/Dev/mashumaro/mashumaro/core/meta/code/builder.py", line 876, in _get_field_packer
    packer = PackerRegistry.get(
  File "/Users/misha/Dev/mashumaro/mashumaro/core/meta/types/common.py", line 86, in get
    expr = packer(spec)
..........
ile "/Users/misha/Dev/mashumaro/mashumaro/core/meta/code/builder.py", line 644, in _add_pack_method_lines
    field_types = self.field_types
  File "/Users/misha/Dev/mashumaro/mashumaro/core/meta/code/builder.py", line 151, in field_types
    return self.__get_field_types()
  File "/Users/misha/Dev/mashumaro/mashumaro/core/meta/code/builder.py", line 118, in __get_field_types
    field_type_hints = typing.get_type_hints(self.cls)
  File "/Users/misha/.asdf/installs/python/3.10.9/lib/python3.10/typing.py", line 1833, in get_type_hints
    value = _eval_type(value, base_globals, base_locals)
  File "/Users/misha/.asdf/installs/python/3.10.9/lib/python3.10/typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/Users/misha/.asdf/installs/python/3.10.9/lib/python3.10/typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
  File "/Users/misha/.asdf/installs/python/3.10.9/lib/python3.10/typing.py", line 309, in inner
    return cached(*args, **kwds)
  File "/Users/misha/.asdf/installs/python/3.10.9/lib/python3.10/typing.py", line 1038, in __hash__
    return hash((self.__origin__, self.__args__))
  File "/Users/misha/.asdf/installs/python/3.10.9/lib/python3.10/typing.py", line 1038, in __hash__
    return hash((self.__origin__, self.__args__))
  File "/Users/misha/.asdf/installs/python/3.10.9/lib/python3.10/typing.py", line 1038, in __hash__
    return hash((self.__origin__, self.__args__))
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Tried with 10000 max depth, same result.

Any ideas right of the bat?

**Comment by Fatal1ty** [comment] 2023-01-09 19:29
Merged and will be available in an upcoming release.

**Comment by mishamsk** [comment] 2023-01-09 21:08
@Fatal1ty thanks a lot!

**Comment by Fatal1ty** [comment] 2023-01-10 13:45
Fixed in [3.3.1](https://github.com/Fatal1ty/mashumaro/releases/tag/v3.3.1).

**Closed by Fatal1ty** 2023-01-10 13:45 UTC
Labels: bug
